In [1]:
import numpy as np
from sklearn.model_selection import train_test_split

In [2]:
x = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
y = np.array([0,0,1,0,1,0,0,0,0,0,1,1,1,0,1,0,1,1,1,1])

In [59]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.2)

In [60]:
x_train

array([14, 15, 16,  4, 17,  1,  9, 18,  5,  2, 12,  7, 11, 10,  8, 13])

In [61]:
len(x_train)

16

In [62]:
x_test

array([ 6,  3, 20, 19])

In [63]:
len(x_test)

4

In [64]:
y_train

array([0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1])

In [65]:
y_test

array([0, 1, 1, 1])